-- Cricket Universe V1.1 Manager Online
-- Run once in Supabase SQL Editor.
-- IMPORTANT: use only your public anon/publishable key in the browser.

create extension if not exists pgcrypto;

create table if not exists public.profiles (
  user_id uuid primary key references auth.users(id) on delete cascade,
  data jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now()
);

create table if not exists public.tournaments (
  id uuid primary key default gen_random_uuid(),
  owner_user_id uuid not null references auth.users(id) on delete cascade,
  local_ref text,
  name text not null,
  visibility text not null default 'public' check (visibility in ('public','private')),
  settings jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create table if not exists public.tournament_teams (
  id uuid primary key default gen_random_uuid(),
  tournament_id uuid not null references public.tournaments(id) on delete cascade,
  local_team_id text not null,
  team_name text not null,
  squad jsonb not null default '[]'::jsonb,
  manager_user_id uuid references auth.users(id) on delete set null,
  unique(tournament_id, local_team_id)
);

create table if not exists public.manager_invites (
  id uuid primary key default gen_random_uuid(),
  tournament_team_id uuid not null unique references public.tournament_teams(id) on delete cascade,
  invite_code text not null unique,
  owner_user_id uuid not null references auth.users(id) on delete cascade,
  claimed_at timestamptz
);

create table if not exists public.matches (
  id uuid primary key default gen_random_uuid(),
  tournament_id uuid references public.tournaments(id) on delete cascade,
  host_user_id uuid not null references auth.users(id) on delete cascade,
  share_code text not null unique,
  team_a_local_id text not null,
  team_b_local_id text not null,
  status text not null default 'lobby' check(status in ('lobby','live','completed','cancelled')),
  visibility text not null default 'public' check(visibility in ('public','private')),
  decision_timeout integer not null default 30,
  state jsonb not null default '{}'::jsonb,
  result jsonb,
  created_at timestamptz not null default now(),
  started_at timestamptz,
  completed_at timestamptz,
  updated_at timestamptz not null default now()
);

create table if not exists public.lineup_submissions (
  id uuid primary key default gen_random_uuid(),
  match_id uuid not null references public.matches(id) on delete cascade,
  tournament_team_id uuid not null references public.tournament_teams(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  lineup jsonb not null,
  submitted_at timestamptz not null default now(),
  unique(match_id,tournament_team_id)
);

create table if not exists public.manager_actions (
  id uuid primary key default gen_random_uuid(),
  match_id uuid not null references public.matches(id) on delete cascade,
  tournament_team_id uuid not null references public.tournament_teams(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  decision_id text not null,
  action_type text not null,
  payload jsonb not null,
  consumed boolean not null default false,
  created_at timestamptz not null default now()
);

create table if not exists public.match_events (
  id bigint generated by default as identity primary key,
  match_id uuid not null references public.matches(id) on delete cascade,
  ball_no text,
  event_type text not null,
  payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

alter table public.profiles enable row level security;
alter table public.tournaments enable row level security;
alter table public.tournament_teams enable row level security;
alter table public.manager_invites enable row level security;
alter table public.matches enable row level security;
alter table public.lineup_submissions enable row level security;
alter table public.manager_actions enable row level security;
alter table public.match_events enable row level security;

-- PROFILE
drop policy if exists profiles_own_select on public.profiles;
create policy profiles_own_select on public.profiles for select to authenticated using (auth.uid()=user_id);
drop policy if exists profiles_own_insert on public.profiles;
create policy profiles_own_insert on public.profiles for insert to authenticated with check (auth.uid()=user_id);
drop policy if exists profiles_own_update on public.profiles;
create policy profiles_own_update on public.profiles for update to authenticated using (auth.uid()=user_id) with check (auth.uid()=user_id);

-- TOURNAMENTS
drop policy if exists tournaments_read on public.tournaments;
create policy tournaments_read on public.tournaments for select to anon, authenticated using (
  visibility='public' or owner_user_id=auth.uid() or exists (
    select 1 from public.tournament_teams tt where tt.tournament_id=tournaments.id and tt.manager_user_id=auth.uid()
  )
);
drop policy if exists tournaments_owner_insert on public.tournaments;
create policy tournaments_owner_insert on public.tournaments for insert to authenticated with check (owner_user_id=auth.uid());
drop policy if exists tournaments_owner_update on public.tournaments;
create policy tournaments_owner_update on public.tournaments for update to authenticated using (owner_user_id=auth.uid()) with check (owner_user_id=auth.uid());

-- TOURNAMENT TEAMS
drop policy if exists tournament_teams_read on public.tournament_teams;
create policy tournament_teams_read on public.tournament_teams for select to anon, authenticated using (
  manager_user_id=auth.uid() or exists(select 1 from public.tournaments t where t.id=tournament_teams.tournament_id and (t.visibility='public' or t.owner_user_id=auth.uid()))
);
drop policy if exists tournament_teams_owner_insert on public.tournament_teams;
create policy tournament_teams_owner_insert on public.tournament_teams for insert to authenticated with check (
  exists(select 1 from public.tournaments t where t.id=tournament_id and t.owner_user_id=auth.uid())
);
drop policy if exists tournament_teams_owner_update on public.tournament_teams;
create policy tournament_teams_owner_update on public.tournament_teams for update to authenticated using (
  exists(select 1 from public.tournaments t where t.id=tournament_id and t.owner_user_id=auth.uid())
);

-- MANAGER INVITES: only tournament owner can read/create them.
drop policy if exists manager_invites_owner_read on public.manager_invites;
create policy manager_invites_owner_read on public.manager_invites for select to authenticated using (owner_user_id=auth.uid());
drop policy if exists manager_invites_owner_insert on public.manager_invites;
create policy manager_invites_owner_insert on public.manager_invites for insert to authenticated with check (owner_user_id=auth.uid());

-- Secure manager-code claim. The friend supplies only the code.
create or replace function public.claim_manager_code(p_code text)
returns jsonb
language plpgsql
security definer
set search_path=public
as $$
declare
  inv public.manager_invites;
  tt public.tournament_teams;
begin
  if auth.uid() is null then raise exception 'Sign in first'; end if;
  select * into inv from public.manager_invites where upper(invite_code)=upper(p_code) for update;
  if inv.id is null then raise exception 'Invalid manager code'; end if;
  select * into tt from public.tournament_teams where id=inv.tournament_team_id for update;
  if tt.manager_user_id is not null and tt.manager_user_id <> auth.uid() then raise exception 'This team has already been claimed'; end if;
  update public.tournament_teams set manager_user_id=auth.uid() where id=tt.id;
  update public.manager_invites set claimed_at=coalesce(claimed_at,now()) where id=inv.id;
  return jsonb_build_object('tournament_team_id',tt.id,'tournament_id',tt.tournament_id,'local_team_id',tt.local_team_id,'team_name',tt.team_name);
end $$;
grant execute on function public.claim_manager_code(text) to authenticated;

-- MATCHES: public matches readable by signed-in users; participants can read private matches.
drop policy if exists matches_read on public.matches;
create policy matches_read on public.matches for select to anon, authenticated using (
 visibility='public' or host_user_id=auth.uid() or exists(
   select 1 from public.tournament_teams tt where tt.tournament_id=matches.tournament_id and tt.manager_user_id=auth.uid() and tt.local_team_id in (matches.team_a_local_id,matches.team_b_local_id)
 )
);
drop policy if exists matches_host_insert on public.matches;
create policy matches_host_insert on public.matches for insert to authenticated with check (host_user_id=auth.uid());
drop policy if exists matches_host_update on public.matches;
create policy matches_host_update on public.matches for update to authenticated using (host_user_id=auth.uid()) with check (host_user_id=auth.uid());

-- LINEUPS: host or the assigned team manager.
drop policy if exists lineup_read on public.lineup_submissions;
create policy lineup_read on public.lineup_submissions for select to authenticated using (
 user_id=auth.uid() or exists(select 1 from public.matches m where m.id=match_id and m.host_user_id=auth.uid())
);
drop policy if exists lineup_insert on public.lineup_submissions;
create policy lineup_insert on public.lineup_submissions for insert to authenticated with check (
 user_id=auth.uid() and exists(select 1 from public.tournament_teams tt where tt.id=tournament_team_id and tt.manager_user_id=auth.uid())
);
drop policy if exists lineup_update on public.lineup_submissions;
create policy lineup_update on public.lineup_submissions for update to authenticated using (
 user_id=auth.uid() and exists(select 1 from public.tournament_teams tt where tt.id=tournament_team_id and tt.manager_user_id=auth.uid())
) with check (user_id=auth.uid());

-- MANAGER ACTIONS: manager can submit only for own assigned team; host reads/consumes.
drop policy if exists actions_insert on public.manager_actions;
create policy actions_insert on public.manager_actions for insert to authenticated with check (
 user_id=auth.uid() and exists(select 1 from public.tournament_teams tt where tt.id=tournament_team_id and tt.manager_user_id=auth.uid())
);
drop policy if exists actions_read on public.manager_actions;
create policy actions_read on public.manager_actions for select to authenticated using (
 user_id=auth.uid() or exists(select 1 from public.matches m where m.id=match_id and m.host_user_id=auth.uid())
);
drop policy if exists actions_host_update on public.manager_actions;
create policy actions_host_update on public.manager_actions for update to authenticated using (
 exists(select 1 from public.matches m where m.id=match_id and m.host_user_id=auth.uid())
);

-- EVENTS: host inserts. Public match events are readable; private participants can read.
drop policy if exists events_insert on public.match_events;
create policy events_insert on public.match_events for insert to authenticated with check (
 exists(select 1 from public.matches m where m.id=match_id and m.host_user_id=auth.uid())
);
drop policy if exists events_read on public.match_events;
create policy events_read on public.match_events for select to anon, authenticated using (
 exists(select 1 from public.matches m where m.id=match_events.match_id and (
   m.visibility='public' or m.host_user_id=auth.uid() or exists(
     select 1 from public.tournament_teams tt where tt.tournament_id=m.tournament_id and tt.manager_user_id=auth.uid()
   )
 ))
);

create index if not exists matches_share_code_idx on public.matches(share_code);
create index if not exists match_events_match_id_idx on public.match_events(match_id,id);
create index if not exists manager_actions_match_decision_idx on public.manager_actions(match_id,decision_id,consumed);
